{% set xorg_name = "libXfixes" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: 39f115d72d9c5f8111e4684164d3d68cc1fd21f9b27ff2401b08fddfc0f409ba

build:
  number: 0
  # xorg-libxdmcp, libxcb, libx11, libice aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - pkg-config
    - gnuconfig
    - make
    - autoconf
    - automake
    - gettext
    - libtool
  host:
    - pthread-stubs
    - xorg-xorgproto
    - xorg-libx11 >=1.6,<2
    # Additional constraintless xorg-libx11 dep below is for conda-build to add potential pinning to.
    - xorg-libx11
    - xorg-util-macros
  run:
    - {{ pin_compatible('xorg-libx11') }}

test:
  commands:
    {% set lib_idents = [ "Xfixes" ] %}
    {% for lib_ident in lib_idents %}
    - test -f $PREFIX/lib/lib{{ lib_ident }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ lib_ident }}.so     # [linux]
    {% endfor %}

about:
  home: https://www.x.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxfixes
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libxfixes
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org library for simple protocol fixes.

extra:
  recipe-maintainers:
    - pkgw
